Add class diagrams
vetand/code-statistics pull request #2
Opened 2021-03-08 09:23 UTC by vetand

Диаграммы классов для первого и самого главного кейса (сбор статистики). Редактирование режимов будет добавлено позже, текущая архитектура это позволяет.

2021-03-11 13:05 UTC, nvamelichev commented
Файлы *.png почему-то пустые, не могу посмотреть диаграммы :-(

Чуток глянул ваши CRC-карточки. Вспомогательные классы (типа парсера командной строки) **свои делать не надо** и добавлять их в модель **не надо**. Заюзайте любую современную библиотеку для разбора командной строки, скажем, picocli, JCommander или args4j

2021-03-11 17:56 UTC, nvamelichev requested changes
- [ ]  Вообще
    - [ ] Пожалуйста, экспортируйте PlantUML-диаграммы в SVG. Это векторный формат, и при его использовании а) диаграммы будут хорошо масштабироваться и б) диффы будут более добрые текстовые (т.к. SVG - это XML)
- [ ]  По динамической модели (`dynamicUML.png`)
    - [ ]  Пока вижу только диаграмму юзкейсов, показывающую ну оооочень обобщённо, кто кого из классов юзает. Хочу деталей! :-) Покажите, например, как классы будут взаимодействовать, чтобы по всему проекту посчитать количество пустых строк и строк-комментариев, напечатать результат в консоль и экспортировать в машиночитаемом формате (JSON).
- [ ] По статической модели `staticUML.png`:
    - [ ] Пожалуйста, уберите классы, которых в CRC-карточках нет
    - [ ] Все связи кроме наследования у вас - это направленные ассоциации. Хотелось бы уточнений: какие-то из них на самом деле композиции ("целое содержит часть и управляет её жизненным циклом"), какие-то - агрегации ("целое может содержать часть, но не управляет её жизненным циклом"), а какие - просто ассоциации (например, "объект класса `X` использует объект класса `Y`, переданный в метод `z()`, чтобы сделать то-то и то-то").
    - [ ] Для композиций и агрегаций обязательно проставьте кратность: сколько объектов с каждой стороны связи могут в ней поучаствовать.
    - [ ] Внутри отчёта (`Report`) вижу у вас список пар ключ-значение (`List<Pair<String,String>>`) лучше наверное описать как `Map` (если по ключу одно значение) или `Multimap` (если по ключу может быть несколько значений). `Map`/`Multimap` - это как раз соответствие ключ-значение, с точки зрения математики это называется "отображение".
    - [ ] Мелкие замечания по оформлению:
        - [ ]  В UML принят Pascal/Go-стиль объявления. А именно, тип поля декларируется после имени поля, точно так же с функциями. (`x: String`, `process(x: RList): int`). Поправьте, пожалуйста, объявления ваших полей и методов.
        - [ ]  ";" в конце объявлений полей и методов не нужны. Уберите их - диаграмма будет проще читаться :-)

2021-03-11 17:56 UTC, nvamelichev commented on CRC.md
> +Подклассы: `FileReport`, `ProjectReport`, `JSONreport`
Класс `Report` смешивает две ответственности в одну: 
* ваши пункты 1) и 3): сохранять и загружать данные отчёта;
* ваш пункт 2): генерировать по этим данным некоторый вывод для пользователя. 

SRP (Single Responsibility Principle) рекомендует эти две ответственности **разделить** на два класса. Тогда вы сможете, например, сохранить отчёт по конкретному исходному файлу (FileReport) как в текстовом формате, так и в JSON/HTML/YAML/XML/whatever (JSONWriter, TextWriter, HTMLWriter, ...).

Помните, я на семинаре приводил пример про систему логгирования (слайд 13, по "S" из SOLID - **Single Responsibility Principle**)? Там было так: за генерацию лог-сообщения отвечает один класс (`Logger`), за форматирование сгенерированного сообщения - другой (`Layout`), а за вывод сообщения в консоль/в файл/в сеть - вообще третий (`Appender`). Это позволяет изменять все три части независимо друг от друга.

2021-03-11 17:56 UTC, nvamelichev commented on CRC.md
> +Ответственность: хранит информацию о том, какую именно статистику мы хотим получить в виде массива классов `Statistics`.
"в виде массива" - слишком подробно, а вдруг вы потом захотите сделать `ArrayList` или даже `HashMap`? :-)
можно просто "хранит информацию о показателях статистики (`Statistics`), которые будут собраны"

2021-03-11 17:56 UTC, nvamelichev commented on CRC.md
> +### 3) MakeModeCommand (todo)
я правильно понимаю, что это заготовка для сохранения пользовательских настроек (=кастомных режимов сбора статистики)?

2021-03-11 17:57 UTC, nvamelichev commented
В целом - хорошее начало! :+1:

Оставил выше комментарии в виде чек-листа. Очень удобно: можно ставить галочки, когда поправите конкретный пункт :-)

2021-03-11 18:53 UTC, nvamelichev requested changes
Поревьювил ещё, см. обновленный чеклист выше

2021-03-12 09:36 UTC, vetand commented on CRC.md
> +### 3) MakeModeCommand (todo)
Да, так и есть, после того, как сделаем основной кейс, добавим возможность создавать режимы. А так пока хочется хотя бы просто с отчётами разобраться)

2021-03-12 12:00 UTC, nvamelichev commented on CRC.md
> +### 3) MakeModeCommand (todo)
:+1:

2021-03-12 12:10 UTC, nvamelichev requested changes

2021-03-12 12:10 UTC, nvamelichev commented on CRC.md
> +Связанные классы: `Mode` - режим сбора статистики (`--full`, `--base`), `Appender` - класс, выводящий в консоль готовый отформатированный отчёт.
Лучше бы конечно назвать не `Appender`, а более близко к предметной области. Например, `ReportWriter` - "выводящий отчёты" :-)

2021-03-12 12:10 UTC, nvamelichev commented on CRC.md
> +Ответственность: хранит информацию о том, какую именно статистику мы хотим получить в виде классов `Statistics`.
я бы вообще убрал "в виде классов ...".

просто "хранит информацию о том, какие типы статистики вы собираете". Связанные классы: Statistics (методы сбора статистики), ModeLibrary

2021-03-12 12:15 UTC, nvamelichev commented
По диаграммам:
* Класс JSONReport странный. Мне казалось, что вы собираете отчёт по проекту (ProjectReport) путём агрегации отчётов по отдельным файликам (FileReport). А вывод в отчёта в формате простой текст/JSON/HTML/XML/... - это уже задача Layout'а скорее всего (типа TextLayout/JsonLayout/HTMLLayout/XMLLayout/...)
* Чем отличается CollectStatCommand.execute() ("выполнить") от call ("вызвать")? Почему один из них возвращает число, а другой - Appender?

2021-03-12 12:16 UTC, nvamelichev requested changes
По диаграммам:
* Класс JSONReport странный. Мне казалось, что вы собираете отчёт по проекту (ProjectReport) путём агрегации отчётов по отдельным файликам (FileReport). А вывод в отчёта в формате простой текст/JSON/HTML/XML/... - это уже задача Layout'а скорее всего (типа TextLayout/JsonLayout/HTMLLayout/XMLLayout/...)
* Чем отличается CollectStatCommand.execute() ("выполнить") от call ("вызвать")? Почему один из них возвращает число, а другой - Appender?

2021-03-14 14:36 UTC, vetand commented
По поводу интерфейса `Command.call()` - это дефолтная реализация обработки команды из picocli https://picocli.info/. Тут будет практически то же самое.

2021-03-16 12:18 UTC, nvamelichev requested changes
В целом всё хорошо, осталось поправить один минорный момент и можно мёржить :+1:

2021-03-16 12:18 UTC, nvamelichev commented on dynamicUML.svg
Тут всё ОК, кроме класса `JSONReport` - его теперь нет, из диаграммы последовательности его тоже нужно удалить.

2021-03-17 10:47 UTC, merged

2021-03-17 13:42 UTC, nvamelichev reviewed
:+1: