added first version closes #10
vetand/code-statistics pull request #6
Opened 2021-04-04 01:44 UTC by timurvankov

2021-04-04 10:14 UTC, vetand requested changes
Всё норм, осталось совсем немного поправить

2021-04-04 10:14 UTC, vetand commented on CodeStats/src/main/java/codestats/ProjectTree.java
> +  private static boolean isValidFile(String filename) {
Добавь какую-нибудь базовую проверку, вроде "можно открыть как текстовый".

2021-04-04 10:14 UTC, vetand commented on CodeStats/src/main/java/codestats/ProjectTree.java
> +    return filename.matches(".*\\.(c$|cpp$|java$)");
Добавь немного побольше расширений (.h .hpp как пример, но их гораздо больше).

2021-04-04 10:14 UTC, vetand commented on CodeStats/src/test/java/codestats/UnitTests.java
>      // мб имя файла неправильное, можно поменять
Сотри коммент

2021-04-05 13:32 UTC, timurvankov commented on CodeStats/src/main/java/codestats/ProjectTree.java
> +  private static boolean isValidFile(String filename) {
что ты имеешь ввиду?

2021-04-05 13:38 UTC, vetand commented on CodeStats/src/main/java/codestats/ProjectTree.java
> +  private static boolean isValidFile(String filename) {
Взять какой-нибудь стандартный механизм открытия текстового файла - открыть и посмотреть, что не вылетело никаких исключений

2021-04-05 13:48 UTC, merged