First version of TextLayout and ProjectReport
vetand/code-statistics pull request #7
Opened 2021-04-05 08:49 UTC by Nolan16

2021-04-05 11:49 UTC, vetand requested changes
Отлично! Осталось совсем чуть-чуть подправить и готово.

2021-04-05 11:49 UTC, vetand commented on CodeStats/src/main/java/codestats/ProjectReport.java
> -public class ProjectReport extends Report {
А всё-таки оставь extend - пусть наша программа выводит и сумму по всему проекту при помощи методов абстрактного Report.  Это скорее всего будет одной из твоих мини-тасок на следующей итерации

2021-04-05 11:49 UTC, vetand commented on CodeStats/src/main/java/codestats/ProjectReport.java
> -    super();
Аналогично

2021-04-05 11:49 UTC, vetand commented on CodeStats/src/main/java/codestats/ProjectReport.java
> -  public void addFileReport(Report fileReport) {
Аналогично, откати пока назад, пусть будет

2021-04-05 20:57 UTC, nvamelichev commented on CodeStats/src/main/java/codestats/ProjectReport.java
> +  HashMap<String, Report> fileStats_;
"я не ревьювер, я просто получил уведомление от гитхаба". нагло врываюсь в ПР с комментариями по кодстайлу и лучшим практикам кодирования:
* Лучше задекларировать наименьший общий интерфейс, который реально используется теми, кто работает с полем. В данном случае, это интерфейс `Map` вместо конкретного подкласса `HashMap`. Конкретный подкласс стоит указывать в тех случаях, когда вам реально нужен оттуда метод и/или поле, которых в родительском интерфейсе/базовом классе нет, и осмысленно в общий интерфейс их не вынесли.
* `приватноеПоле_` это C++ style, в джавке принято писать просто `fileStats`, без суффиксов и префиксов. Если понадобится различить поле класса и аргумент метода, используйте `this` животворящий:
```
public MyClass(That that) {
    this.that = that; // полю класса присваивается значение аргумента метода
}
```
На андроидах, правда, есть секта любителей префикса "m_" для приватных полей ("member"), но 99.9% разработчиков так не пишут :-)
* забыт модификатор `private` - по умолчанию это поле класса будет доступно всем классам в пакете, где лежит класс `ProjectReport`

2021-04-06 21:35 UTC, Nolan16 commented on CodeStats/src/main/java/codestats/ProjectReport.java
> +  HashMap<String, Report> fileStats_;
Полагаю, что поправим это в следующей реализации

2021-04-07 07:50 UTC, merged